# Generated by Django 5.2.10 on 2026-01-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.CreateModel(
            name='UserTrackLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('WEB_FRONT', '웹 프론트엔드'), ('WEB_BACK', '웹 백엔드'), ('APP_FRONT', '앱 프론트엔드'), ('APP_BACK', '앱 백엔드'), ('GAME', '게임 개발')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='해당 트랙의 레벨 (0~6)')),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True, help_text='레벨 진단 일시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'track'], name='accounts_us_user_id_0de7d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'track'), name='uq_user_track_level')],
            },
        ),
    ]
