# Generated by Django 5.2.10 on 2026-01-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YOUTUBE", "YOUTUBE"),
                            ("INFLEARN", "INFLEARN"),
                            ("VELOG", "VELOG"),
                            ("BLOG", "BLOG"),
                            ("ETC", "ETC"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "VIDEO"),
                            ("ARTICLE", "ARTICLE"),
                            ("COURSE", "COURSE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("WEB_FRONT", "WEB_FRONT"),
                            ("WEB_BACK", "WEB_BACK"),
                            ("APP_FRONT", "APP_FRONT"),
                            ("APP_BACK", "APP_BACK"),
                            ("GAME", "GAME"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level_min", models.PositiveSmallIntegerField(default=0)),
                ("level_max", models.PositiveSmallIntegerField(default=6)),
                ("estimated_time", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "learning_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearningResourceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_tags",
                        to="learning.learningresource",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_tags",
                        to="learning.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="learningresource",
            name="tags",
            field=models.ManyToManyField(
                related_name="resources",
                through="learning.LearningResourceTag",
                to="learning.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="learningresourcetag",
            index=models.Index(fields=["tag"], name="learning_le_tag_id_1a68f8_idx"),
        ),
        migrations.AddConstraint(
            model_name="learningresourcetag",
            constraint=models.UniqueConstraint(
                fields=("resource", "tag"), name="uq_learning_resource_tags"
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["platform"], name="learning_le_platfor_ef90d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["content_type"], name="learning_le_content_37c87f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["track"], name="learning_le_track_ecc62f_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["level_min", "level_max"], name="learning_le_level_m_071736_idx"
            ),
        ),
    ]
