# Generated by Django 5.2.10 on 2026-01-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("roadmaps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("WEB_FRONT", "WEB_FRONT"),
                            ("WEB_BACK", "WEB_BACK"),
                            ("APP_FRONT", "APP_FRONT"),
                            ("APP_BACK", "APP_BACK"),
                            ("GAME", "GAME"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("starred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reflections",
                        to="roadmaps.roadmapitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="reflections_user_id_471546_idx",
                    ),
                    models.Index(
                        fields=["user", "starred"],
                        name="reflections_user_id_10be5b_idx",
                    ),
                    models.Index(
                        fields=["track", "created_at"],
                        name="reflections_track_05d546_idx",
                    ),
                ],
            },
        ),
    ]
