# Generated by Django 5.2.10 on 2026-01-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("WEB_FRONT", "WEB_FRONT"),
                            ("WEB_BACK", "WEB_BACK"),
                            ("APP_FRONT", "APP_FRONT"),
                            ("APP_BACK", "APP_BACK"),
                            ("GAME", "GAME"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_tags",
                        to="roadmaps.roadmap",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_tags",
                        to="learning.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roadmap",
            name="tags",
            field=models.ManyToManyField(
                related_name="roadmaps",
                through="roadmaps.RoadmapTag",
                to="learning.tag",
            ),
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="리소스 삭제 시 과거 로드맵 기록 보호 위해 PROTECT 권장",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roadmap_items",
                        to="learning.learningresource",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="roadmaps.roadmap",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["roadmap", "is_completed"],
                        name="roadmaps_ro_roadmap_85ed7f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roadmap", "order_no"), name="uq_roadmap_items_order_no"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="roadmaptag",
            index=models.Index(fields=["tag"], name="roadmaps_ro_tag_id_d861cf_idx"),
        ),
        migrations.AddConstraint(
            model_name="roadmaptag",
            constraint=models.UniqueConstraint(
                fields=("roadmap", "tag"), name="uq_roadmap_tags"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["user", "track", "is_completed"],
                name="roadmaps_ro_user_id_1fe566_idx",
            ),
        ),
    ]
