# Generated by Django 5.2.10 on 2026-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='track',
            field=models.CharField(choices=[('WEB_FRONT', '웹 프론트엔드'), ('WEB_BACK', '웹 백엔드'), ('APP_FRONT', '앱 프론트엔드'), ('APP_BACK', '앱 백엔드'), ('GAME', '게임 개발')], max_length=20),
        ),
    ]
